package com.example.heroesapp.models

data class Heroes(
    val id : Int,
    val name : String,
    val description : String,
    val image : String,
    val PublisherId : Int
) {
    companion object {
        val heroes = mutableListOf<Heroes>(

            // MARVEL HEROES

            // SOLO
            Heroes(1,"Spider-Man","Spider-Man, traducido en ocasiones como el Hombre Araña,es un superhéroe ficticio creado por los estadounidenses Stan Lee y Steve Ditko, e introducido en el cómic Amazing Fantasy n.° 15, publicado por Marvel Comics en agosto de 1962. Se trata de un superhéroe que emplea sus habilidades sobrehumanas, reminiscentes de una araña, para combatir a otros supervillanos que persiguen fines siniestros.","https://static.wikia.nocookie.net/ficcion-sin-limites/images/6/6b/Spidey.png/revision/latest?cb=20210226124716&path-prefix=es",0),
            Heroes(2,"Daredevil","Daredevil es un personaje de Marvel Comics creado por Stan Lee y Bill Everett. Apareció por primera vez en Daredevil #1 (abril de 1964). Matt Murdock, el alter ego de Daredevil, es un abogado ciego que desarrolló sentidos agudizados después de ser expuesto a radiación nuclear en un accidente de niño. Utiliza sus habilidades para luchar contra el crimen en las calles de Hell’s Kitchen, Nueva York, como el superhéroe Daredevil.","https://static.wikia.nocookie.net/character-level/images/d/d9/MC_Daredevil_TR.png/revision/latest/scale-to-width-down/375?cb=20190901013719",0),
            Heroes(3,"Black Panther","La Pantera Negra (T'Challa) (inglés: Black Panther) es un superhéroe de la compañía estadounidense Marvel Comics, creado por Stan Lee y Jack Kirby para el número 52 de The Fantastic Four. Es el primer superhéroe de tez negra de la historia de Marvel y se debe destacar que el personaje fue creado con anterioridad al Partido Pantera Negra, el cual fue fundado en octubre del mismo año. Es el rey y protector de la ficticia nación africana de Wakanda. Además de poseer habilidades mejoradas logradas a través de rituales antiguos de Wakanda de beber la esencia de la hierba en forma de corazón, T'Challa también confía en su dominio de la ciencia, el entrenamiento físico riguroso, las habilidades de combate mano a mano y el acceso a la riqueza y la avanzada tecnología de Wakanda para combatir a sus enemigos que amenacen su cultura y tradiciones.","https://static.wikia.nocookie.net/versus-compendium/images/d/dc/BP.png/revision/latest?cb=20181009193143",0),
            Heroes(4,"Capitana Marvel ","Carol Davers es una superheroína ficticia que aparece en cómics estadounidenses publicados por Marvel Comics. Fue creada por el escritor Roy Thomas y el artista Gene Colan, Carol apareció por primera vez como oficial de la Fuerza Aérea de los Estados Unidos y colega del superhéroe Kree llamado Mar-Vell en Marvel Super-Heroes # 13 (marzo de 1968). Danvers más tarde se convirtió en la primera encarnación de Ms. Marvel en Ms. Marvel #1 (enero de 1977) después de que su ADN se fusionara con el de Mar-Vell durante una explosión, otorgándole poderes sobrehumanos.","https://static.wikia.nocookie.net/death-battle-en-espanol/images/b/b8/Captain_Marvel.png/revision/latest?cb=20230517191419&path-prefix=es",0),

            // DESAPARECIERON LOS VENGADORES (?)

            // X MEN
            Heroes(11,"Profesor X","Charles Xavier, también llamado Profesor X, es un superhéroe ficticio que aparece en los cómics estadounidenses publicados por Marvel Comics. El personaje es representado como el fundador y, a veces, líder de los X-Men. Creado por el escritor Stan Lee y el artista/coguionista Jack Kirby, el personaje apareció por primera vez en The X-Men #1 (septiembre de 1963).\n" + "\n" + "Xavier es miembro de una subespecie de humanos conocidos como mutantes, que nacen con habilidades sobrehumanas. Es un telépata excepcionalmente poderoso, que puede leer y controlar la mente de los demás. Para albergar y entrenar mutantes de todo el mundo, dirige una escuela privada en Mansión X en Salem Center, ubicada en el condado de Westchester, Nueva York. Xavier también se esfuerza por servir a un bien mayor mediante la promoción de la coexistencia pacífica y la igualdad entre humanos y mutantes en un mundo donde el fanatismo anti-mutante está muy extendido.","https://static.wikia.nocookie.net/marvelcrossroads/images/b/bd/Professor_X_%28Marvel_Resuited%29.png/revision/latest?cb=20181025201729",0),
            Heroes(12,"Cíclope","Cíclope (Scott Summers) es un personaje ficticio que aparece en los cómics estadounidenses publicados por Marvel Comics y es miembro fundador de los X-Men. Creado por el escritor Stan Lee y el artista Jack Kirby, el personaje apareció por primera vez en el cómic The X-Men de 1963, en la Edad de Plata de los cómics. Cíclope es miembro de una subespecie de humanos conocidos como mutantes, que nacen con habilidades sobrehumanas. Cíclope emite poderosos rayos de energía de sus ojos y solo puede controlar los rayos con la ayuda de gafas especiales que debe usar en todo momento. Por lo general, se le considera el primero de los X-Men, un equipo de héroes mutantes que luchan por la paz y la igualdad entre mutantes y humanos, uno de los principales líderes del equipo.","https://static.wikia.nocookie.net/ficcion-sin-limites/images/9/9c/Cyclops_MvC2.png/revision/latest/scale-to-width-down/328?cb=20230807165611&path-prefix=es",0),
            Heroes(13,"Wolverine","Wolverine, cuyo nombre de nacimiento es James Howlett (también conocido como James Logan o simplemente Logan), es un superhéroe y antihéroe ficticio que aparece en los cómics publicados por Marvel Comics, principalmente en asociación con los X-Men. Es un mutante que posee sentidos afinados a los animales, capacidades físicas mejoradas, poderosa capacidad de regeneración conocida como un factor de curación, y tres garras retráctiles en cada mano. Wolverine ha sido representado de diversas formas como miembro de los X-Men, Alpha Flight, Fuerza-X y Los Vengadores.","https://static.wikia.nocookie.net/vsbattles/images/d/dc/Marvel_Comics_Wolverine_%28Render%29.png/revision/latest?cb=20190404035926",0),
            Heroes(14,"Bestia","Bestia (Dr. Henry Philip 'Hank' McCoy) es un superhéroe ficticio que aparece en los cómics publicados por Marvel Comics. Es un miembro fundador del equipo de superhéroes mutantes conocidos como los X-Men. Cuando fue introducido por primera vez, Bestia era un mutante que poseía fuerza y agilidad sobrehumanas, con manos y pies de gran tamaño, aunque por lo demás parecía ser un humano normal. A lo largo de su historia, Bestia sufre transformaciones progresivas de su fisonomía, ganando de forma permanente características físicas cada vez más bestiales. Estas incluyeron piel azul y rasgos felinos en su primer transformación y simiescos en la última. Su nivel físico se incrementó a niveles aún mayores, al igual que sus sentidos.","https://static.wikia.nocookie.net/death-battle-fanon-wiki-en-espanol/images/9/9c/Beast_%28Marvel%29.png/revision/latest?cb=20221126035434&path-prefix=es",0),
            Heroes(15,"Storm","Tormenta (Storm, en el inglés original), alias de Ororo Iqadi Munroe, es una superheroína ficticia de la editorial estadounidense Marvel Comics. Esta superheroína apareció por primera vez en el cómic Giant-Size X-Men #1 (mayo de 1975) y fue creada por el guionista Len Wein y el dibujante Dave Cockrum. La caracterizan sus ojos azules, pelo blanco y tez oscura. Ella es capaz de controlar el clima y la atmósfera y se considera que es uno de los mutantes más poderosos del planeta.","https://upload.wikimedia.org/wikipedia/en/3/34/Storm_%28Ororo_Munroe%29.png",0),
            // 4 FANTASTICOS
            Heroes(16,"Señor Fantastico","El Sr. Fantástico (Reed Richards) es un superhéroe ficticio que aparece en los cómics estadounidenses publicados por Marvel Comics. Es miembro fundador de Los 4 Fantásticos. Reed posee un dominio de la ingeniería mecánica, aeroespacial y eléctrica, la química, todos los niveles de la física y la biología humana y alienígena. BusinessWeek enumeró al Mr. Fantástico como uno de los 10 mejores personajes ficticios más inteligentes en los cómics estadounidenses.1​ Él es el inventor de la nave espacial que fue bombardeada por la radiación cósmica en su viaje inaugural, otorgando a Los 4 Fantásticos sus poderes. Reed ganó la capacidad de estirar su cuerpo en cualquier forma que lo desee.","https://static.wikia.nocookie.net/marveldatabase/images/a/ad/Reed_Richards_%28Earth-616%29_from_Fantastic_Four_Vol_1_570_0002.png/revision/latest?cb=20100117192027",0),
            Heroes(17,"Mujer Invisible","La Mujer Invisible (Susan Storm), anteriormente conocida como la Chica Invisible, es una superheroína ficticia que aparece en cómics estadounidenses publicados por Marvel Comics. El personaje es miembro fundador de los Cuatro Fantásticos y fue la primera superheroína creada por Marvel durante la Era de la Plata de los Cómics. Sue Richards recibió sus poderes después de haber estado expuesta a una tormenta cósmica. Su poder primario se ocupa de las ondas de luz, lo que le permite hacerse invisible a sí misma y a los demás. También puede proyectar poderosos campos de energía psiónica invisible que utiliza para una variedad de efectos ofensivos y defensivos. Richards desempeña un papel central en la vida de su hermano menor flameante, Johnny Storm, su brillante marido Reed Richards, su amigo íntimo Ben Grimm, y sus hijos (Franklin y Valeria).","https://static.wikia.nocookie.net/tasw/images/1/15/The_Invisible_Woman.png/revision/latest?cb=20220317035101",0),
            Heroes(18,"Antorcha Humana","La Antorcha Humana (Jonathan 'Johnny' Storm) es un superhéroe ficticio que aparece en los cómics estadounidenses publicados por Marvel Comics. Él es un miembro fundador de los 4 Fantásticos. Creado por el escritor Stan Lee y el artista Jack Kirby, el personaje apareció por primera vez en Fantastic Four, Vol. 1, #1 (noviembre de 1961). Un similar, sin relación con el personaje del mismo nombre y poderes había sido creado en 1939 por el escritor-artista Carl Burgos para la compañía predecesora de Marvel Comics, Timely Comics.","https://static.wikia.nocookie.net/mua/images/d/d3/Dlc_img_15.png/revision/latest?cb=20210729062913",0),
            Heroes(19,"La Mole","Thing (Benjamin Jacob 'Ben' Grimm), traducido como la Cosa en España y la Mole en Hispanoamérica, es un superhéroe de ficción que aparece en los cómics estadounidenses publicados por Marvel Comics. El personaje es miembro fundador de Los 4 Fantásticos. Thing fue creado por el escritor y editor Stan Lee y el artista Jack Kirby, y apareció por primera vez en The Fantastic Four # 1 (noviembre de 1961).","https://static.wikia.nocookie.net/omniversal-battlefield/images/4/4a/Thing.png/revision/latest?cb=20210927235638",0),

            // DC HEROES

            // JUSTICE LEAGUE.
            Heroes(20,"Superman","Superman (en español: Superhombre) es un superhéroe ficticio que apareció por primera vez por Action Comics, perteneciente al grupo de cómics estadounidenses publicados por DC Comics. El personaje fue creado por el escritor estadounidense Jerry Siegel y el artista canadiense Joe Shuster, y debutó en el cómic Action Comics #1 (fecha de portada: junio de 1938 y publicado el 18 de abril de 1938),cuando ambos se encontraban viviendo en Cleveland, Ohio. Superman ha sido adaptado a varios otros medios, que incluyen seriales de radio, novelas, películas, programas de televisión, teatro y videojuegos. Superman nació en el planeta ficticio Krypton y recibió el nombre de nacimiento Kal-El. Cuando era un bebé, sus padres, el científico Jor-El y su esposa Lara Lor-Van, lo enviaron a la Tierra en una pequeña nave espacial momentos antes de que Krypton fuera destruido en un cataclismo natural. Su nave aterrizó en el campo estadounidense, cerca de la ciudad ficticia de Smallville. Fue encontrado y adoptado por los agricultores Jonathan y Martha Kent, quienes lo llamaron Clark Kent. Clark desarrolló varias habilidades sobrehumanas, como una fuerza increíble y una piel impermeable. Sus padres adoptivos le aconsejaron que usara sus habilidades en beneficio de la humanidad y decidió luchar contra el crimen como un justiciero. Para proteger su privacidad, se pone un traje colorido y usa el alias 'Superman' cuando lucha contra el crimen.","https://upload.wikimedia.org/wikipedia/en/1/1a/Superman_%28circa_1960s%29.png",1),
            Heroes(21,"Batman","Batman (conocido inicialmente como The Bat-Man y en español como el Hombre Murciélago) es un superhéroe ficticio de cómic creado por los estadounidenses Bob Kane y Bill Finger, y propiedad de DC Comics. Apareció por primera vez en la historia titulada «El caso del sindicato químico» de la revista Detective Comics N.º 27, lanzada por la editorial National Publications el 30 de marzo de 1939. La identidad secreta de Batman es Bruce Wayne (Bruno Díaz en algunos países de habla hispana), un multimillonario magnate empresarial y filántropo dueño de Empresas Wayne en Gotham City. Después de presenciar el asesinato de sus padres, el Dr. Thomas Wayne y Martha Wayne en un violento y fallido asalto cuando era niño, juró venganza contra los criminales, un juramento moderado por el sentido de la justicia. Bruce Wayne se entrena física e intelectualmente y crea un traje inspirado en los murciélagos para combatir el crimen, con sus gadgets de combate del batcinturón y sus vehículos","https://static.wikia.nocookie.net/death-battle-en-espanol/images/d/d1/Batman.png/revision/latest/scale-to-width-down/250?cb=20220730023454&path-prefix=es",1),
            Heroes(22,"Mujer Maravilla","La Mujer Maravilla (en inglés: Wonder Woman) es una superheroína ficticia creada por William Moulton Marston y H. G. Peter para la editorial DC Comics. Es una princesa guerrera de las Amazonas, pueblo ficticio basado en el de las amazonas de la mitología griega. En su tierra natal es conocida como la princesa Diana de Temiscira pero fuera de esta utiliza la identidad secreta de Diana Prince. Está dotada de una amplia gama de poderes superhumanos y habilidades de combate de batalla superiores, gracias a sus dones obtenidos de los dioses y su amplio entrenamiento. Ella posee un gran arsenal de armas, incluyendo entre las principales el Lazo de la Verdad, un par de brazaletes mágicos indestructibles, su tiara, que sirve como arma, y en algunos relatos, en la edad de oro, tuvo un avión invisible. Pero más adelante, se le fue mostrando con la capacidad de volar cada vez con mayor frecuencia por lo que el avión invisible fue dejando de utilizarse.","https://static.wikia.nocookie.net/death-battle-fanon-wiki-en-espanol/images/9/96/Mujer_Maravilla.png/revision/latest?cb=20190323022056&path-prefix=es",1),
            Heroes(23,"The Flash","Flash (conocido también como The Flash y traducido en español: Destello) es el nombre de varios superhéroes ficticios que aparecen en los cómics estadounidenses publicados por DC Comics. Creado por el escritor Gardner Fox y el artista Harry Lampert, el 'Flash' original apareció por primera vez en Flash Comics #1 (fecha de portada de enero de 1940 / mes de noviembre de 1939). Apodado el Corredor Escarlata, todas las encarnaciones de Flash poseen súper velocidad, que incluye la capacidad de correr, moverse y pensar extremadamente rápido, también puede atravesar la materia sólida, usar reflejos sobrehumanos y aparentemente violar ciertas leyes de la física, como superar la velocidad de la luz.","https://static.wikia.nocookie.net/vsbattles/images/9/9b/Post_Crisis_Flash_render_1.png/revision/latest?cb=20230109075944",1),
            Heroes(24,"Linterna Verde","Linterna Verde (en inglés: Green Lantern) es el nombre de varios superhéroes del universo de ficción de la editorial DC Comics, los cuales se caracterizan por portar un anillo de poder y una batería en forma de linterna que otorga al portador la capacidad de crear manifestaciones de luz verde sólida con ellos. Combaten el mal con estos anillos que los brindan una variedad de poderes extraordinarios, todos los cuales provienen de la imaginación, la intrepidez y el espectro electromagnético de la fuerza de voluntad emocional. Los personajes son por lo general mostrados como miembros de los Green Lantern Corps, la organización policial intergaláctica a la pertenecen todos los Linternas Verdes. Mientras que el anillo del Linterna Verde original de la Edad de Oro es impulsado por la magia, los anillos utilizados por los Green Lantern Corps, son creaciones tecnológicas de los Guardianes del Universo, los cuales son asignados a aquellos candidatos que son considerados dignos de portarlos. Debido al poder del anillo, Linterna Verde es considerado uno de los superhéroes más poderosos del Universo DC, siendo capaces de lograr contener incluso Supernovas y Agujeros Negros. Varios de sus enemigos también son considerados como de los más trascendentales villanos del Universo DC como lo son Parallax y el Antimonitor, mientras que Sinestro es su villano más habitual.","https://static.wikia.nocookie.net/death-battle-fanon-wiki-en-espanol/images/7/7b/Hal_Jordan.png/revision/latest?cb=20190511153824&path-prefix=es",1),
            Heroes(25,"Aquaman","Aquaman (Arthur Curry) (en español: Hombre Acuático) es un superhéroe que aparece en los cómics estadounidenses publicados por DC Comics. Creado por el artista Paul Norris y el escritor Mort Weisinger, el personaje debutó en More Fun Comics # 73 (noviembre de 1941). Inicialmente, una característica de respaldo en los títulos de antología de DC, Aquaman más tarde protagonizó varios volúmenes de una serie de cómics en solitario. Durante los últimos años de la década de 1950 y 1960, el período de recuperación de superhéroes conocido como la Edad de Plata, fue miembro fundador de la Liga de la Justicia. En la Edad Moderna de la década de 1990, los escritores interpretaron el personaje de Aquaman más seriamente, con historias que representan el peso de su papel como rey de la Atlántida","https://static.wikia.nocookie.net/death-battle-fanon-wiki-en-espanol/images/8/84/Aquaman.png/revision/latest?cb=20190918015708&path-prefix=es",1),
            Heroes(26,"Detective Marciano","El Detective Marciano (J'onn J'onzz) (en inglés: Martian Manhunter) es un superhéroe que aparece en los cómics estadounidenses publicados por DC Comics. Creado por el escritor Joseph Samachson y diseñado por el artista Joe Certa, el personaje apareció por primera vez en la historia The Manhunter from Mars en Detective Comics # 225 (noviembre de 1955). Martian Manhunter es uno de los siete miembros originales de la Liga de la Justicia de América y uno de los seres más poderosos del Universo DC","https://static.wikia.nocookie.net/versus-compendium/images/a/a2/1912498-martian_manhunter_001_02_-removebg-preview.png/revision/latest?cb=20190808045558",1),
            // BATFAMILY
            Heroes(27,"Nightwing","Nightwing (en español: Ala Nocturna) es un superhéroe ficticio que aparece en los cómics estadounidenses publicados por DC Comics. El personaje ha aparecido en varias encarnaciones; la identidad fue adoptada por Dick Grayson cuando se reinventó a sí mismo después de su papel como el compañero justiciero de Batman, Robin.","https://static.wikia.nocookie.net/death-battle-fanon-wiki-en-espanol/images/8/8a/Nightwing.png/revision/latest?cb=20190305054712&path-prefix=es",1),
            Heroes(28,"Red Hood","Red Hood (en español Capucha Roja) es un alias que han portado varios personajes de la editorial DC Comics. El más conocido de todos es Jason Todd, quien asume la identidad de Red Hood en la continuidad principal del Universo DC. Otro famoso portador del alias fue el Joker, quien lo utilizó durante sus inicios en el mundo delictivo.","https://static.wikia.nocookie.net/goldbattles/images/c/c2/N52_Red_Hood.png/revision/latest?cb=20230325024843",1),
            Heroes(29,"Batgirl","Batgirl (en español: Chica Murciélago o Batichica en Hispanoamérica) es el nombre de varias superheroínas ficticias que aparecen en los cómics estadounidenses publicados por DC Comics, representados como contrapartes femeninas del superhéroe Batman. Aunque el personaje Betty Kane se introdujo en la publicación en 1961 por Bill Finger y Sheldon Moldoff como Bat-Girl, fue reemplazada por Barbara Gordon en 1967, quien luego fue identificada como la icónica Batgirl. El personaje debutó en Detective Comics clasificado como 12 años en adelante # 359, titulado ¡El debut del millón de dólares de Batgirl! (enero de 1967) del escritor Gardner Fox y del artista Carmine Infantino, se presentó como la hija del comisario de policía James Gordon.","https://static.wikia.nocookie.net/death-battle-en-espanol/images/d/d2/Batgirl.png/revision/latest?cb=20201116183355&path-prefix=es",1),
            Heroes(30,"Robin","Robin es el alias de varios superhéroes ficticios que aparecen en los cómics estadounidenses publicados por DC Comics. El personaje fue creado originalmente por Bob Kane, Bill Finger y Jerry Robinson, para servir como contraparte menor del superhéroe Batman. Tras el reinicio de continuidad de 2011 The New 52, Tim Drake fue revisado como si hubiera asumido el título de Red Robin, y Jason Todd, que operaba como Red Hood, estaba reparando lentamente su relación con Batman. Dick Grayson retomó su papel de Nightwing y Stephanie Brown fue presentada de nuevo bajo su apodo anterior, Spoiler, en las páginas de Batman Eternal (2014). El relanzamiento de la continuidad de DC Rebirth 2016 comienza con Damian Wayne como Robin, Tim Drake como Red Robin, Jason Todd como Red Hood y Dick Grayson como Nightwing. Los Robins también han aparecido en historias ambientadas en mundos paralelos, debido al antiguo Multiverso del concepto de DC Comics. Por ejemplo, en el original Tierra-2, Dick Grayson nunca adoptó el nombre Nightwing, y continúa operando como Robin hasta la edad adulta. En la continuidad Tierra-2 de New 52, Robin es Helena Wayne, hija de Batman y Catwoman, quien quedó varada en la Tierra de la continuidad principal y toma el nombre de Cazadora.","https://static.wikia.nocookie.net/characterprofile/images/a/a8/Untitled_drawing_-_2021-12-13T125824.113.png/revision/latest?cb=20211213205835",1),
            // TEENS TITANS
            Heroes(31,"Beast Boy","Garfield Mark Gar Logan, personaje conocido como Beast Boy (nombre traducido a veces al español como Chico Bestia) o también Changeling es un superhéroe que aparece en los cómics estadounidenses publicados por DC Comics. Creado por el escritor Arnold Drake y el artista Bob Brown, es un cambiante que posee la capacidad de metamorfosearse en cualquier criatura que elija. El personaje apareció por primera vez en The Doom Patrol # 99 (noviembre de 1965) y generalmente se lo representa como miembro de la Patrulla Condenada y los Jóvenes Titanes.","https://hyperborea.org/flash/images/beastboy.png",1),
            Heroes(32,"Starfire","Starfire (en español: Fuego Estelar) (Princesa Koriand'r) es una superheroína ficticia que aparece en los cómics publicados por DC Comics. Debutó en una historia preliminar insertada en DC Comics Presents #26 (octubre de 1982) y fue creada por Marv Wolfman y George Pérez. El nombre Starfire apareció por primera vez en un cómic de DC en la historia The Answer Man of Space, en Mystery in Space #73, febrero de 1962, escrito por Gardner Fox.","https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/6df83f41-ae35-4de3-aae1-4eb9d87a6782/dfau4zl-cbbf92ba-002b-492f-b67a-28792d57796a.png/v1/fill/w_1280,h_1967/starfire__dc__render_by_ssundpool_dfau4zl-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTk2NyIsInBhdGgiOiJcL2ZcLzZkZjgzZjQxLWFlMzUtNGRlMy1hYWUxLTRlYjlkODdhNjc4MlwvZGZhdTR6bC1jYmJmOTJiYS0wMDJiLTQ5MmYtYjY3YS0yODc5MmQ1Nzc5NmEucG5nIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.sJNebA-pojUAoHnf5YbdAEr4_Jn3S1IMdg1aDfz0ohQ",1),
            Heroes(33,"Cyborg","Cyborg (en español: Cíborg) (conocido como Victor Vic Stone) es un superhéroe ficticio que aparece en los cómics estadounidenses publicados por DC Comics. El personaje fue creado por el escritor Marv Wolfman y el artista George Pérez y apareció por primera vez en un suplemento especial en DC Comics Presents #26 (octubre de 1980). Cyborg es conocido como un miembro de los Jóvenes Titanes. Sin embargo, en septiembre de 2011, Cyborg fue establecido como un miembro fundador de la Liga de la Justicia como parte del reinicio de la continuidad de DC de 2011 hasta el evento DC Rebirth, donde este suceso fue cambiado una vez más. El personaje es un pastiche del personaje de Marvel Comics, Deathlok.","https://static.wikia.nocookie.net/one-minute-melee/images/a/a3/Cyborg.png/revision/latest?cb=20180515183131&path-prefix=es",1),
            Heroes(34,"Raven","Raven (en español: Cuervo) es una superheroína ficticia que aparece en los cómics estadounidenses publicados por DC Comics. El personaje apareció por primera vez en un inserto especial en DC Comics Presents # 26 (octubre de 1980), y fue creado por el escritor Marv Wolfman y el artista George Pérez. Hija de un padre demonio (Trigon) y madre humana (Arella), Raven es una empática que puede teletransportarse y controlar su alma, que puede luchar físicamente, así como actuar como los ojos y oídos de Raven lejos de su físico cuerpo. Ella es un miembro prominente del equipo de superhéroes Los Jóvenes Titanes. El personaje también se conoce con el alias de Rachel Roth como un falso nombre civil.","https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8d40e9ca-1974-4a87-bbfa-165264db741b/dgtvjeg-c3e845e4-6a4b-4d05-ae6b-e363430b564c.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzhkNDBlOWNhLTE5NzQtNGE4Ny1iYmZhLTE2NTI2NGRiNzQxYlwvZGd0dmplZy1jM2U4NDVlNC02YTRiLTRkMDUtYWU2Yi1lMzYzNDMwYjU2NGMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.oCvkSabkUCdIQHoS_IVDNgye30wgYSye_Ds1ODviBVk",1)
        )
    }
}
